# Generated by Django 5.1.2 on 2024-10-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_remove_restaurant_contact_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
